-- +goose Up
-- +goose StatementBegin
SELECT 'up SQL query';
-- +goose StatementEnd
INSERT INTO compliments (text) VALUES ('%s, ты самый лучший человек на планете');
INSERT INTO compliments (text) VALUES ('%s, ты прекрасный человечек');
INSERT INTO compliments (text) VALUES ('%s, у тебя все получится!');
INSERT INTO compliments (text) VALUES ('%s, улыбнись!');
INSERT INTO compliments (text) VALUES ('%s, твоя улыбка светит, как солнце');
INSERT INTO compliments (text) VALUES ('%s, этому миру нужны такие люди, как ты');
INSERT INTO compliments (text) VALUES ('%s, ты неповторимый и совершенный человечек');
INSERT INTO compliments (text) VALUES ('%s, ты вызываешь восхищение');
INSERT INTO compliments (text) VALUES ('%s, твоя добрая энергия притягивает всех вокруг');
INSERT INTO compliments (text) VALUES ('%s, ты источник вдохновения');
INSERT INTO compliments (text) VALUES ('%s, никогда не сдавайся');
INSERT INTO compliments (text) VALUES ('%s, невозможно быть милее, чем ты!');
INSERT INTO compliments (text) VALUES ('%s, потрясающе умеешь слушать и поддерживать!');
INSERT INTO compliments (text) VALUES ('%s, c тобой каждый день становится особенным');
INSERT INTO compliments (text) VALUES ('%s, ты очень необычный и уникальный человек');
INSERT INTO compliments (text) VALUES ('%s, прекрасного тебе дня!');
INSERT INTO compliments (text) VALUES ('%s, замечательного тебе дня!');
INSERT INTO compliments (text) VALUES ('%s, ты всех уделаешь сегодня!');
INSERT INTO compliments (text) VALUES ('%s, у тебя потрясающие причёска и улыбка!');
INSERT INTO compliments (text) VALUES ('%s, ты удивительный и прекрасный человек.');
INSERT INTO compliments (text) VALUES ('%s, ты  воплощение  мечты');
INSERT INTO compliments (text) VALUES ('%s, все будет прекрасно, улыбайся!');
INSERT INTO compliments (text) VALUES ('%s, ты мотивируешь  быть лучшим');
INSERT INTO compliments (text) VALUES ('%s, ты просто в фантастической форме!');
INSERT INTO compliments (text) VALUES ('%s, никто на свете не сравнится с тобой.');
INSERT INTO compliments (text) VALUES ('%s, ты превосходный человечек');
INSERT INTO compliments (text) VALUES ('%s, в тебя невозможно не влюбиться');
INSERT INTO compliments (text) VALUES ('%s, ты просто блистательный человечек!');
INSERT INTO compliments (text) VALUES ('%s, твои чарующие глаза притягивают как магниты');
INSERT INTO compliments (text) VALUES ('%s, ну давай же, надери им всем зад!');
INSERT INTO compliments (text) VALUES ('%s, ты — невероятно талантливая и креативная личность');
INSERT INTO compliments (text) VALUES ('%s, твой смех — самая сладкая мелодия');
INSERT INTO compliments (text) VALUES ('%s, ты  умеешь создавать магию в повседневных моментах');
INSERT INTO compliments (text) VALUES ('%s, ты словно магия, оживляющая серые будни');
INSERT INTO compliments (text) VALUES ('%s, ты наполняешь мир красотой и смыслом');
INSERT INTO compliments (text) VALUES ('%s, тебя ждет сегодня успех');
INSERT INTO compliments (text) VALUES ('%s, все будет хорошо!');
INSERT INTO compliments (text) VALUES ('%s, интересного, насыщенного, яркого дня! Приветливых улыбок и хорошего настроения! ');
INSERT INTO compliments (text) VALUES ('%%, улыбнись, ты оч красивый человек');
INSERT INTO compliments (text) VALUES ('%s, делай легче, делай играуючи, КАЙФУЙ');
INSERT INTO compliments (text) VALUES ('%s, у тебя золотое сердце');
INSERT INTO compliments (text) VALUES ('%s, твоя доброта не знает границ');
INSERT INTO Compliments (text) VALUES ('%s, твоя положительная энергия заразительна');
INSERT INTO compliments (text) VALUES ('%s, у тебя красивая душа');
INSERT INTO compliments (text) VALUES ('%s, твой интеллект заметен');
INSERT INTO compliments (text) VALUES ('%s, у тебя блестящий ум');
INSERT INTO compliments (text) VALUES ('%s, твоя улыбка делает мой день ярче');
INSERT INTO compliments (text) VALUES ('%s, вы обладаете замечательными талантами');
INSERT INTO compliments (text) VALUES ('%s, твоя решимость вдохновляет');
INSERT INTO compliments (text) VALUES ('%s, вы меняете мир, куда бы вы ни пошли');
INSERT INTO compliments (text) VALUES ('%s, твойе присутствие приносит радость окружающим');
INSERT INTO compliments (text) VALUES ('%s, твой оптимизм освежает');
INSERT INTO compliments (text) VALUES ('%s, вы настоящий образец для подражания');
INSERT INTO Compliments (text) VALUES ('%s, твое сострадание не знает границ');
INSERT INTO compliments (text) VALUES ('%s, твое творчество не знает границ');
INSERT INTO compliments (text) VALUES ('%s, у тебя невероятная трудолюбие');
INSERT INTO compliments (text) VALUES ('%s, твои идеи всегда новаторские');
INSERT INTO compliments (text) VALUES ('%s, твоя дружба бесценна');
INSERT INTO compliments (text) VALUES ('%s, у тебя душевная улыбка');
INSERT INTO compliments (text) VALUES ('%s, твоя страсть вдохновляет');
INSERT INTO compliments (text) VALUES ('%s, у тебя природный талант заставлять людей чувствовать себя особенными');
INSERT INTO compliments (text) VALUES ('%s, твой позитивный настрой заразителен');
INSERT INTO compliments (text) VALUES ('%s, вы исключительный слушатель');
INSERT INTO compliments (text) VALUES ('%s, твое чувство юмора украшает любую комнату');
INSERT INTO compliments (text) VALUES ('%s, у тебя уникальный и красивый взгляд');
INSERT INTO compliments (text) VALUES ('%s, твоя преданность достойна восхищения');
INSERT INTO compliments (text) VALUES ('%s, твоя смелость вдохновляет');
INSERT INTO compliments (text) VALUES ('%s, у тебя замечательное чувство стиля');
INSERT INTO compliments (text) VALUES ('%s, твойе присутствие поднимает настроение');
INSERT INTO compliments (text) VALUES ('%s, твоя щедрость не знает границ');
INSERT INTO compliments (text) VALUES ('%s, у тебя невероятная способность мотивировать других');
INSERT INTO compliments (text) VALUES ('%s, твоя решимость не имеет себе равных');
INSERT INTO compliments (text) VALUES ('%s, у тебя необыкновенный дар решать проблемы');
INSERT INTO compliments (text) VALUES ('%s, твоя уверенность вдохновляет');
INSERT INTO compliments (text) VALUES ('%s, у тебя природный талант объединять людей');
INSERT INTO compliments (text) VALUES ('%s, твоя мудрость не по годам');
INSERT INTO compliments (text) VALUES ('%s, у тебя очаровательная внешность');
INSERT INTO compliments (text) VALUES ('%s, твоя стойкость замечательна');
INSERT INTO compliments (text) VALUES ('%s, у тебя невероятный взгляд на детали');
INSERT INTO compliments (text) VALUES ('%s, твой позитив заразителен');
INSERT INTO compliments (text) VALUES ('%s, у тебя притягательная личность');
INSERT INTO compliments (text) VALUES ('%s, твоя забота всеми оценена');
INSERT INTO compliments (text) VALUES ('%s, у тебя потрясающая способность вдохновлять других');
INSERT INTO compliments (text) VALUES ('%s, твоя решимость непоколебима');
INSERT INTO compliments (text) VALUES ('%s, у тебя невероятное чувство юмора');
INSERT INTO compliments (text) VALUES ('%s, твой позитив скрашивает даже самые мрачные дни');
INSERT INTO compliments (text) VALUES ('%s, у тебя необыкновенная способность заставлять людей чувствовать');
INSERT INTO compliments (text) VALUES ('%s, у тебя все получится!');
INSERT INTO compliments (text) VALUES ('%s, сегодня твой день сиять!');
INSERT INTO compliments (text) VALUES ('%s, твои возможности безграничны, используй их.');
INSERT INTO compliments (text) VALUES ('%s, успех начинается с веры в себя.');
INSERT INTO compliments (text) VALUES ('%s, Вы способны на удивительные вещи.');
INSERT INTO compliments (text) VALUES ('%s, Ваша тяжелая работа окупится, продолжайте идти');
INSERT INTO compliments (text) VALUES ('%s, никогда не отказывайся от своей мечты.');
INSERT INTO compliments (text) VALUES ('%s, используйте каждую возможность, которая появляется на вашем пути.');
INSERT INTO compliments (text) VALUES ('%s, миру нужны ваши уникальные таланты.');
INSERT INTO compliments (text) VALUES ('%s, верьте в свои способности, они необыкновенны.');
INSERT INTO compliments (text) VALUES ('%s, продолжайте двигаться вперед, вас ждет величие.');
INSERT INTO compliments (text) VALUES ('%s, лови момент и сделай его своим.');
INSERT INTO compliments (text) VALUES ('%s, верьте в себя, и другие тоже поверят.');
INSERT INTO compliments (text) VALUES ('%s, не бойтесь рисковать, он приведет к вознаграждению.');
INSERT INTO compliments (text) VALUES ('%s, ваша решимость откроет двери, о которых вы даже не подозревали.');
INSERT INTO compliments (text) VALUES ('%s, помните, что каждая неудача – это ступенька к успеху.');
INSERT INTO compliments (text) VALUES ('%s, продолжайте учиться, продолжайте расти, продолжайте достигать.');
INSERT INTO compliments (text) VALUES ('%s, ваш потенциал не знает границ.');
INSERT INTO compliments (text) VALUES ('%s, у вас есть все, что нужно, чтобы изменить ситуацию.');
INSERT INTO compliments (text) VALUES ('%s, ваша страсть приведет вас к величию.');
INSERT INTO compliments (text) VALUES ('%s, успех не за горами, продолжайте.');
INSERT INTO compliments (text) VALUES ('%s, верь в себя, даже если никто другой не верит.');
INSERT INTO compliments (text) VALUES ('%s, ваш упорный труд и самоотверженность будут вознаграждены.');
INSERT INTO compliments (text) VALUES ('%s, никогда не недооценивайте силу своей мечты.');
INSERT INTO compliments (text) VALUES ('%s, успех – это не пункт назначения, а путешествие.');
INSERT INTO compliments (text) VALUES ('%s, пусть твоя решимость превзойдет твои страхи.');
INSERT INTO compliments (text) VALUES ('%s, каждый ваш шаг приближает вас к успеху.');
INSERT INTO compliments (text) VALUES ('%s, поверьте себе, вы способны на величие.');
INSERT INTO compliments (text) VALUES ('%s, успех приходит к тем, кто верит и упорствует.');
INSERT INTO compliments (text) VALUES ('%s, принимайте вызовы, они делают вас сильнее.');
INSERT INTO compliments (text) VALUES ('%s, никогда не позволяй никому притупить твой блеск.');
INSERT INTO compliments (text) VALUES ('%s, ваш позитивный настрой — ваш самый большой актив.');
INSERT INTO compliments (text) VALUES ('%s, успех – это результат упорного труда и настойчивости.');
INSERT INTO compliments (text) VALUES('%s, верьте в себя, чудеса случаются каждый день.');
INSERT INTO compliments (text) VALUES ('%s, не ждите возможностей, создавайте их.');
INSERT INTO compliments (text) VALUES ('%s, у вас есть силы воплотить свои мечты в реальность.');
INSERT INTO compliments (text) VALUES ('%s, ваш путь к успеху начинается с одного шага.');

-- +goose Down
-- +goose StatementBegin
SELECT 'down SQL query';
TRUNCATE compliments;
-- +goose StatementEnd
