// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ainurqa95/mood-lifter/internal/repository (interfaces: UserRepository,MessageRepository,ComplimentRepository)
//
// Generated by this command:
//
//	mockgen -destination ./mock/repository.go -package mock . UserRepository,MessageRepository,ComplimentRepository
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	model "github.com/ainurqa95/mood-lifter/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockUserRepository is a mock of UserRepository interface.
type MockUserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepositoryMockRecorder
}

// MockUserRepositoryMockRecorder is the mock recorder for MockUserRepository.
type MockUserRepositoryMockRecorder struct {
	mock *MockUserRepository
}

// NewMockUserRepository creates a new mock instance.
func NewMockUserRepository(ctrl *gomock.Controller) *MockUserRepository {
	mock := &MockUserRepository{ctrl: ctrl}
	mock.recorder = &MockUserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepository) EXPECT() *MockUserRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRepository) Create(arg0 context.Context, arg1 string, arg2 *model.UserInfo) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRepositoryMockRecorder) Create(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRepository)(nil).Create), arg0, arg1, arg2)
}

// GetByPeriodWithLimitOffset mocks base method.
func (m *MockUserRepository) GetByPeriodWithLimitOffset(arg0 context.Context, arg1 []int, arg2, arg3 int) ([]model.UserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByPeriodWithLimitOffset", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]model.UserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByPeriodWithLimitOffset indicates an expected call of GetByPeriodWithLimitOffset.
func (mr *MockUserRepositoryMockRecorder) GetByPeriodWithLimitOffset(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByPeriodWithLimitOffset", reflect.TypeOf((*MockUserRepository)(nil).GetByPeriodWithLimitOffset), arg0, arg1, arg2, arg3)
}

// UpdatePeriodType mocks base method.
func (m *MockUserRepository) UpdatePeriodType(arg0 context.Context, arg1 int, arg2 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePeriodType", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePeriodType indicates an expected call of UpdatePeriodType.
func (mr *MockUserRepositoryMockRecorder) UpdatePeriodType(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePeriodType", reflect.TypeOf((*MockUserRepository)(nil).UpdatePeriodType), arg0, arg1, arg2)
}

// MockMessageRepository is a mock of MessageRepository interface.
type MockMessageRepository struct {
	ctrl     *gomock.Controller
	recorder *MockMessageRepositoryMockRecorder
}

// MockMessageRepositoryMockRecorder is the mock recorder for MockMessageRepository.
type MockMessageRepositoryMockRecorder struct {
	mock *MockMessageRepository
}

// NewMockMessageRepository creates a new mock instance.
func NewMockMessageRepository(ctrl *gomock.Controller) *MockMessageRepository {
	mock := &MockMessageRepository{ctrl: ctrl}
	mock.recorder = &MockMessageRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessageRepository) EXPECT() *MockMessageRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockMessageRepository) Create(arg0 context.Context, arg1 model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockMessageRepositoryMockRecorder) Create(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockMessageRepository)(nil).Create), arg0, arg1)
}

// MockComplimentRepository is a mock of ComplimentRepository interface.
type MockComplimentRepository struct {
	ctrl     *gomock.Controller
	recorder *MockComplimentRepositoryMockRecorder
}

// MockComplimentRepositoryMockRecorder is the mock recorder for MockComplimentRepository.
type MockComplimentRepositoryMockRecorder struct {
	mock *MockComplimentRepository
}

// NewMockComplimentRepository creates a new mock instance.
func NewMockComplimentRepository(ctrl *gomock.Controller) *MockComplimentRepository {
	mock := &MockComplimentRepository{ctrl: ctrl}
	mock.recorder = &MockComplimentRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockComplimentRepository) EXPECT() *MockComplimentRepositoryMockRecorder {
	return m.recorder
}

// GetRandom mocks base method.
func (m *MockComplimentRepository) GetRandom(arg0 context.Context) (*model.Compliment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRandom", arg0)
	ret0, _ := ret[0].(*model.Compliment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRandom indicates an expected call of GetRandom.
func (mr *MockComplimentRepositoryMockRecorder) GetRandom(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRandom", reflect.TypeOf((*MockComplimentRepository)(nil).GetRandom), arg0)
}
